<!-- RemoteHealth/pom.xml -->
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
                             https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.axolotlj</groupId>
    <artifactId>RemoteHealth</artifactId>
    <version>0.3.5</version>
    <packaging>pom</packaging>

    <!-- Los tres sub-proyectos -->
    <modules>
        <module>core</module>
        <module>desktop</module>
        <module>mobile</module>
    </modules>

    <!-- Versión centralizadas que heredan los hijos                        -->
    <!-- (si cambian sólo lo tocas aquí)                                    -->
    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <maven.compiler.release>17</maven.compiler.release>

        <!-- bibliotecas más usadas -->
        <javafx.version>21.0.6</javafx.version>
        <gluonfx.version>1.0.22</gluonfx.version>
    </properties>

    <!-- repositorios comunes -->
    <repositories>
        <repository>
            <id>jitpack.io</id>
            <url>https://jitpack.io</url>
        </repository>
        <repository>
            <id>gluon-releases</id>
            <url>https://nexus.gluonhq.com/nexus/content/repositories/releases/</url>
        </repository>
    </repositories>

    <!-- plug-in de compilación estándar (heredable) -->
    <build>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-compiler-plugin</artifactId>
                    <version>3.11.0</version>
                    <configuration>
                        <release>${maven.compiler.release}</release>
                    </configuration>
                </plugin>
                
               <plugin>
                    <groupId>com.gluonhq</groupId>
                    <artifactId>gluonfx-maven-plugin</artifactId>
                    <version>${gluonfx.version}</version>
                </plugin>
            </plugins>
        </pluginManagement>
    </build>
</project>
